### ISSUE TITLE
기존 프로그램 조사

### ISSUE THREAD

**Issue by pyowonil** [pyowonil/ConvertSoundToScore#1]
형식 : 기존 프로그램명 ( 링크 주소 ) - 간단한 설명

**Comment by pyowonil** [comment]
AudioScore ( http://www.neuratron.com/audioscore.htm ) - 
1. Create scores from MP3s and CD tracks
2. 16 instruments
3. Send the results directly to Sibelius
4. save MusicXML, NIFF and MIDI files for use in most other music programs such as Finale or Cubase
5. Pitch recognition range F0 to C8 (22Hz to 4186Hz)
6. Timing accuracy down to 1/86th of a second
7. Pitch accuracy 0.3Hz (about 1/100th of a semitone at A4)

Download Link(Demo) : http://www.neuratron.com/downloads.asp

**Comment by pyowonil** [comment]
AmazingMIDI ( http://www.pluto.dti.ne.jp/~araki/amazingmidi/ ) -
1. wav -> mid
2. Freeware

Download Link : 
1. http://www.pluto.dti.ne.jp/~araki/amazingmidi/azmid170.exe (in Japan)
2. http://www.tucows.com/preview/327319.html
3. http://www.simtel.net/product.download.mirrors.php?id=68511

**Comment by pyowonil** [comment]
Transcribe! ( http://www.seventhstring.com/xscribe/overview.html ) -
1. It can change pitch and speed instantly, and you can store and recall any number of named loops
2. Transcribe! offers many features aimed at making the transcription job smoother and easier, including the ability to slow down music without changing its pitch, to analyse chords and show you what notes are present, and the capability of adding markers and textual annotations so you can easily navigate around the track
3. Transcribe! also has a piano keyboard displayed on screen which you can click to play reference notes
4. you must still use your ear and brain to decide which of the peaks in the spectrum are notes being played
5. Transcribe! deals with audio sample data files ( Transcribe! takes no interest in MIDI files )
6. Transcribe! plays and records audio files but it is not an audio editor

Download Link : http://www.seventhstring.com/xscribe/download_windows.html (Windows)

**Comment by parkbogyu** [comment]
Intelliscore (http://www.intelliscore.net/)

FAQ 일부분

How does it work?

It has been said that automated music conversion is the musical equivalent of speech recognition. For this analogy to be true, then polyphonic music conversion is like listening to several conversations going on at once and figuring out all the words spoken by everyone. Perhaps it is due to this extra complexity that the technology of automated music conversion has lagged behind speech recognition.

Conventional wisdom suggests that Fourier transformation and wavelet theory would be the best approaches to polyphonic music conversion and wavelength determination for monophonic conversion. If these methods really worked, however, there would be many more programs out there that claim to automatically convert recorded music to music notation.

Due to the inherent limitations of the above methods, intelliScore uses a combination of new, revolutionary approaches based upon our continuing research in psycho-acoustic physics. The core technology is patented. IntelliScore is now in its seventh generation and combines additional proprietary capabilities.
